# Generated by Django 5.2.12 on 2026-05-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code for UI badge', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for frontend', max_length=50)),
                ('is_builtin', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('user', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail (OAuth)'), ('outlook', 'Outlook / Office 365'), ('imap', 'Generic IMAP')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('label', models.CharField(blank=True, help_text='User-friendly name for this account', max_length=100)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.PositiveIntegerField(blank=True, null=True)),
                ('imap_username', models.CharField(blank=True, max_length=255)),
                ('imap_password', models.CharField(blank=True, max_length=255)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Provider-specific message ID', max_length=500)),
                ('thread_id', models.CharField(blank=True, help_text='Email thread identifier', max_length=500)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, help_text='Plain-text body for NLP processing')),
                ('body_html', models.TextField(blank=True, help_text='Original HTML body')),
                ('snippet', models.CharField(blank=True, max_length=300)),
                ('confidence_score', models.FloatField(blank=True, help_text='0.0–1.0 confidence from AI classifier', null=True)),
                ('is_ai_classified', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='apis.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apis.emailaccount')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(blank=True, max_length=1000)),
                ('email_sender', models.EmailField(blank=True, max_length=254)),
                ('email_snippet', models.CharField(blank=True, max_length=300)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether this feedback has been incorporated into re-training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_feedback', to='apis.category')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_events', to='apis.email')),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_feedback', to='apis.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'category'], name='apis_email_user_id_4f5d50_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'received_at'], name='apis_email_user_id_8eb2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['external_id'], name='apis_email_externa_0f111a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklog',
            index=models.Index(fields=['user', 'is_applied'], name='apis_feedba_user_id_cb1e66_idx'),
        ),
    ]
