# Generated by Django 5.2.12 on 2026-05-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated one-sentence summary of the email content'),
        ),
    ]
