# Generated by Django 5.2.12 on 2026-05-14 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_email_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='action_items',
            field=models.TextField(blank=True, help_text='AI-extracted action items, tasks, or next steps (JSON list or plain text)'),
        ),
        migrations.AddField(
            model_name='email',
            name='deadline_date',
            field=models.DateTimeField(blank=True, help_text='Extracted deadline or due date if present', null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='has_deadline',
            field=models.BooleanField(default=False, help_text='Whether the email mentions a deadline or due date'),
        ),
        migrations.AddField(
            model_name='email',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='AI-flagged as urgent or time-sensitive'),
        ),
        migrations.AddField(
            model_name='email',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', help_text='AI-assigned priority: low / medium / high', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='Whether this feedback has been incorporated into preference memory'),
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(help_text='Provider-specific thread identifier (from Gmail)', max_length=500)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('participants', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated running summary of the entire thread')),
                ('latest_received_at', models.DateTimeField(blank=True, null=True)),
                ('email_count', models.PositiveIntegerField(default=0, help_text='Number of emails in this thread')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='apis.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-latest_received_at'],
                'indexes': [models.Index(fields=['user', 'latest_received_at'], name='apis_emailt_user_id_209d61_idx')],
                'unique_together': {('user', 'thread_id')},
            },
        ),
    ]
