# Generated by Django 5.2.12 on 2026-05-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_email_action_items_email_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'ordering': ['-created_at']},
        ),
    ]
