# Generated by Django 5.2.1 on 2026-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_emailaccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='gmail_labels',
            field=models.JSONField(blank=True, default=list, help_text="Provider label IDs from Gmail (e.g. ['INBOX', 'IMPORTANT', 'CATEGORY_PROMOTIONS'])"),
        ),
    ]
